app:
    resource: "@AppBundle/Controller/Web"
    type:     annotation

app_editor:
    resource: "@AppBundle/Controller/Editor"
    type:     annotation

app_admin:
    resource: "@AppBundle/Controller/Admin"
    type:     annotation

app_api:
    resource: "@AppBundle/Controller/Api"
    type:     annotation

#FoS
fos_user:
  resource: "@FOSUserBundle/Resources/config/routing/all.xml"



