cms:
    resource: "@CmsBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/Web"
    type:     annotation

app_api:
    resource: "@AppBundle/Controller/Api"
    type:     annotation

app_test:
    resource: "@AppBundle/Controller/Test"
    type:     annotation

#FoS
fos_user:
  resource: "@FOSUserBundle/Resources/config/routing/all.xml"



